version: '3'

services:
  contact-list-db:
    image: postgres:12
    container_name: contact-list-db
    environment:
      POSTGRES_PASSWORD: example
  contact-list:
    container_name: contact-list
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./contact-list/:/app
    ports:
      - "8000:8000"
    depends_on:
      - contact-list-db
